export const USER_TOKEN = 'USER_TOKEN'
export const LOADING_SHOW = 'LOADING_SHOW'
export const TOAST_SHOW = 'TOAST_SHOW'
export const CHANGE_TITLE = 'CHANGE_TITLE'
export const SHOW_TOAST = 'SHOW_TOAST'
export const HIDE_TOAST = 'HIDE_TOAST'